config/routes.rb
Railstore::Application.routes.draw do


  #resources :payment_notifications
  match "/payment_notifications/:id" => "payment_notifications#create", :as => :payment_notifications

  root :to => "home#index"
  get "home/index"
  get "admin/index"
  get "admin/unvisible"
  get "admin/makevisible"
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/searches/" => "items#index", :as => :search
  match "/items/destroy/:id" => "items#destroy", :as => :destroy
  match "/items/vote_up/:id" => "items#vote_up", :as => :thumbs_up
  match "/items/vote_down/:id" => "items#vote_down", :as => :thumbs_down
  match "/admin/" => "admin#index", :as => :admin
  match "/download/:id" => "items#download", :as => :download
  resources :items
  match "/message/reply" => "items#reply_message"
  match "/message/create" => "items#message_create", :as => :messages
  match "/my_items" => "items#my_items"
  match "/pay/:id" => "items#pay", :as => :setpaychained
  
  end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_reader :per_page
  @@per_page = 10
  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ? OR desc LIKE ? OR content LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"], :joins => [:tags])
    else
      scoped
    end
  end
  belongs_to :user
  has_many :messages
  has_many :tags
  has_many :payment_notifications
  acts_as_voteable
  accepts_nested_attributes_for :tags, :allow_destroy => :true,
      :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
  validates_presence_of :thumbnail
  validates_presence_of :image_preview
  validates_length_of :title, :minimum => 5
  validates_length_of :desc, :minimum => 50
  validates_associated :tags
  validates_presence_of :tags
      validates_attachment_presence :image_preview
      validates_attachment_presence :thumbnail
      
      
  has_attached_file :image_preview,
                      :url  => "/assets/items/image_preveiw/:id/:style/:basename.:extension",
                      :path => ":rails_root/public/assets/items/image_preveiw/:id/:style/:basename.:extension"
      validates_attachment_size :image_preview, :less_than => 1.megabyte
      validates_attachment_content_type :image_preview, :content_type => ['image/jpeg', 'image/png', 'image/jpg']
      
            
  has_attached_file :thumbnail,     
                      :url  => "/assets/items/thumbnail/:id/:style/:basename.:extension",
                      :path => ":rails_root/public/assets/items/thumbnail/:id/:style/:basename.:extension"
      validates_attachment_size :thumbnail, :less_than => 1.megabyte
      validates_attachment_content_type :thumbnail, :content_type => ['image/jpeg', 'image/png', 'image/jpg']
      
      has_attached_file :download,
                          :url  => "/assets/items/download/:id/:style/:basename.:extension",
                          :path => ":rails_root/public/assets/items/download/:id/:style/:basename.:extension"
          validates_attachment_size :download, :less_than => 20.megabytes
          validates_attachment_content_type :download, :content_type => ['application/zip']
          
    def paypal_url(item, user, notify_url)
          values = {
        	:business => 'railsd_1304622257_biz@gmail.com',
        	:cmd => '_xclick',
        	:return => 'http://localhost:3000/items/' + item.id.to_s,
        	:invoice => item.id.to_s + user.id.to_s,
        	:notify_url => notify_url
          }

          values.merge!({
        	  "amount" => item.price,
        	  "item_name" => item.title,
        	  "item_number" => item.id,
        	})
          "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
    end
      
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :login_required, :except => [:show, :index, :pay]
  
  add_crumb("Items", '/items')
  def index
      @items = Item.search(params[:search]).paginate :page => params[:page]
  end
  
  def new
    add_crumb("Add New", '/items/new')
  	@item = Item.new
  end
  
  def create
   @item = Item.new(params[:item])
   @item.user_id = current_user.id
   @item.tags.each do |tag|
     tag.item_id = @item.id
   end
      if @item.save
            redirect_to @item
      else
            render new_item_path
      end
  end


  def edit
    @item = Item.find(params[:id])
    add_crumb "Edit " + @item.title, request.fullpath
  end

  def show
    @item = Item.find(params[:id])
    add_crumb @item.title, request.fullpath
    if @item.license && @item.price
      @item.price = @item.price.to_s
    end
    up = 0
    down = 0
    @item.votes.each do |v|
      if v.vote
        up += 1
      else
        down += 1
      end
    end
    @up = up
    @down = down
    @messages = @item.messages
    @message = Message.new()
    if @item.visible == false && current_user
      unless @item.user_id == current_user.id || current_user.is_admin
        redirect_to root_url, :notice => "Unfortunately you can't access this page since you're not signed in."
      end
    end
  end
  
  def destroy
    i = Item.find(params[:id])
    i.destroy
    redirect_to items_path
 end
  
  def update
     @item = Item.find(params[:id])
     if ! current_user.is_admin
       params[:item][:price] = @item.price
      end
     if @item.update_attributes(params[:item])
        redirect_to :action => 'show', :id => @item
     else
        render :action => 'edit'
     end
  end
    
   def message_create
    @user = User.find(current_user.id)
    @item = Item.find(params[:message][:item_id])
    @message = Message.new(params[:message])
    @message.user_id = @user.id
    @message.item_id = @item.id
    if @message.save
      redirect_to "/items/#{@item.id}"
     else
      render :new
    end
  end
  

  
  def my_items
    
  end
  
  def vote_up
    @user = current_user
    @item = Item.find(params[:id])
    if @user.vote_exclusively_for(@item)
      redirect_to @item
    end
  end
  def vote_down
    @user = current_user
    @item = Item.find(params[:id])
    if @user.vote_exclusively_against(@item)
      redirect_to @item
    end
  end
  
  def download
    @item = Item.find(params[:id])
    send_file "#{RAILS_ROOT}/public" + @item.download.to_s, :type=>"application/zip" 
  end

end

app/views/items/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/items/_form.html.erb
<script type="text/javascript">
jQuery(document).ready( function() {
	if( ! jQuery('#item_license').is(':checked') ) {
		jQuery('#price_wrap').css('display', 'none');
	}
	jQuery('#item_license').change( function() {
		jQuery('#price_wrap').slideToggle(400, function() {
			if( jQuery(this).is(':hidden') ) {
				jQuery(this).find('input').attr('disabled', 'disabled');
			} else {
				jQuery(this).find('input').removeAttr('disabled');
			}
		});
	});
});
</script>
<% @item.tags.build %>
<%= form_for @item, :html => { :multipart => true } do |i| %>
<%= render "error_messages", :target => @item %>
  <%= i.label :title %>
  <%= i.text_field :title %><br />

  <%= i.label :desc %>
  <%= i.text_area :desc %><br />

  <%= render :partial => 'tags/form',
             :locals => {:form => i} %>

	<%= i.label :gems_included %>
	<%= i.text_field :gems_included %><br />
	
	<%= i.label :live_preview %>
	<%= i.text_field :live_preview %><br />
	
	<%= i.label :thumbnail %>
	<%= i.file_field :thumbnail %> <br />
	
	<%= i.label :image_preview %>
	<%= i.file_field :image_preview %><br />
	
	<%= i.label :download %>
	<%= i.file_field :download %><br />
	
	
	<% if current_user.is_admin or request.fullpath.include? 'new' %>
	<%= i.label :license  %>
	<%= i.check_box :license %>Commercial Product
	<div id="price_wrap">
		<%= i.label :price %>
		<%= i.text_field :price %>
	</div>
	<% end %>
  <%= i.submit %>
<% end %>

app/views/items/_message_form.html.erb
<%= form_for @message do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :content, "Your Comment" %><br />
    <%= f.text_area :content, :rows => 8 %>
  </p>
  <%= f.hidden_field :item_id, :value => @item.id %>
  <p><%= f.submit "Post Comment" %></p>
<% end %>

app/views/items/_reply_message_form.html.erb
<%= form_for @message do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :content, "Your Comment" %><br />
    <%= f.text_area :content, :rows => 8 %>
  </p>
  <%= f.hidden_field :item_id, :value => @item.id %>
  <%= f.hidden_field :parent_id %>
  <p><%= f.submit "Post Comment" %></p>
<% end %>

app/views/items/edit.html.erb
<%= render :partial => 'items/form',
           :locals => {:item => @item} %>

app/views/items/index.html.erb
<%= form_tag(search_path, :method => "get") do %>
  <%= search_field_tag(:search) %>
  <%= submit_tag("Search") %>
<% end %>
<% @items.each do |item| %>
<% if item.visible %>
<%= image_tag item.thumbnail.url, :width => "50", :height => "50" %>
<h3><%= link_to item.title, item %></h3>
<p><%= item.desc %></p>
<% end %>
<% end %>
<%= will_paginate @items %>

app/views/items/my_items.html.erb
<h2>Your Published Items</h2>
<% current_user.items.each do |item|
	if item.visible %>
		<%= link_to item.title, item %><br />
		<%
	end
end %>
<h2>Your Upload Queue</h2>
<% current_user.items.each do |item|
	unless item.visible %>
		<%= link_to item.title, item %><br />
		<%
	end
end %>

app/views/items/new.html.erb
<%= render :partial => 'items/form',
           :locals => {:item => @item} %>

app/views/items/pay.html.erb
<%= @transaction.response %>

app/views/items/show.html.erb
<script type="text/javascript">
	jQuery(document).ready( function() {
		jQuery('.reply').click( function(e) {
			e.preventDefault();
			jQuery('#form-' + jQuery(this).attr('id')).slideToggle();
		});
	});
</script>
<% if ! @item.visible %>
This item is currently on queue. It will not be public until we review it.
<% end %>
<h2><%= @item.title %></h2>
<p class="desc"><%= @item.desc %></p><br />
<%= image_tag @item.image_preview.url %><br />
Tags:
<% @item.tags.each do |tags| %>
<% tags.content.to_s.split.each do |tag| %>
<%= link_to tag, search_path + "/?search=" + tag %>
<% end %>
<% end %><br />
<% if @item.price %>
<%=
@item.price
%>$
<%= link_to "Purchase", @item.paypal_url(@item, current_user, payment_notifications_url) %>
<%= @item.payment_notifications %>
<% end %>
<%= link_to "Thumbs Up", thumbs_up_path %><%= @up %>
<%= link_to "Thumbs Down", thumbs_down_path %><%= @down %><br />
<% unless !current_user
	if current_user.id == @item.user_id || current_user.is_admin %>
<%= link_to "Delete", destroy_path, :method=>:delete %> <br />
<%= link_to "Edit", edit_item_path %>
<% end
end %>


<%= nested_messages @messages.arrange(:order => :created_at) %>


<%= render "message_form" %>